"""
Q-CRA Engine — CRA Report Generator for Web (Multilingual)
============================================================
Q-CORE Systems | qcore.systems

Generates CRA compliance PDF in English, Czech, or German.
Language auto-detected from domain TLD or manually selected.
"""

import hashlib
import json
import os
import secrets
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# Register Unicode fonts
_UNICODE_FONT = "Helvetica"
_UNICODE_FONT_BOLD = "Helvetica-Bold"

# Find bundled fonts (shipped with project) or system fonts
_FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")
_FONT_PATHS = [
    _FONT_DIR,                                          # Bundled in project
    "/usr/share/fonts/truetype/dejavu/",                # Linux system
]

def _find_font(filename):
    for d in _FONT_PATHS:
        p = os.path.join(d, filename)
        if os.path.exists(p):
            return p
    return None

try:
    _f_regular = _find_font("DejaVuSans.ttf")
    _f_bold = _find_font("DejaVuSans-Bold.ttf")
    _f_italic = _find_font("DejaVuSans-Oblique.ttf")
    _f_boldit = _find_font("DejaVuSans-BoldOblique.ttf")

    if _f_regular and _f_bold:
        pdfmetrics.registerFont(TTFont("DejaVu", _f_regular))
        pdfmetrics.registerFont(TTFont("DejaVu-Bold", _f_bold))
        if _f_italic:
            pdfmetrics.registerFont(TTFont("DejaVu-Italic", _f_italic))
        if _f_boldit:
            pdfmetrics.registerFont(TTFont("DejaVu-BoldItalic", _f_boldit))
        registerFontFamily("DejaVu", normal="DejaVu", bold="DejaVu-Bold",
                          italic="DejaVu-Italic" if _f_italic else "DejaVu",
                          boldItalic="DejaVu-BoldItalic" if _f_boldit else "DejaVu-Bold")
        _UNICODE_FONT = "DejaVu"
        _UNICODE_FONT_BOLD = "DejaVu-Bold"
    elif os.path.exists("C:/Windows/Fonts/arial.ttf"):
        pdfmetrics.registerFont(TTFont("Arial", "C:/Windows/Fonts/arial.ttf"))
        pdfmetrics.registerFont(TTFont("Arial-Bold", "C:/Windows/Fonts/arialbd.ttf"))
        pdfmetrics.registerFont(TTFont("Arial-Italic", "C:/Windows/Fonts/ariali.ttf"))
        pdfmetrics.registerFont(TTFont("Arial-BoldItalic", "C:/Windows/Fonts/arialbi.ttf"))
        registerFontFamily("Arial", normal="Arial", bold="Arial-Bold",
                          italic="Arial-Italic", boldItalic="Arial-BoldItalic")
        _UNICODE_FONT = "Arial"
        _UNICODE_FONT_BOLD = "Arial-Bold"
except Exception:
    pass

VERSION = "2.1.0"
COMPANY = "Q-CORE Systems"
WEBSITE = "qcore.systems"

C_PRIMARY = HexColor("#0A1628")
C_ACCENT = HexColor("#00E5FF")
C_SUCCESS = HexColor("#00C853")
C_WARNING = HexColor("#FFB300")
C_DANGER = HexColor("#FF3B5C")
C_NEUTRAL = HexColor("#B0BEC5")
C_BG = HexColor("#F0F4F8")
C_TEXT = HexColor("#1A1A2E")
C_DIM = HexColor("#6B7280")

TLD_LANG_MAP = {".cz": "cs", ".sk": "cs", ".de": "de", ".at": "de", ".ch": "de"}

def detect_language(hostname: str) -> str:
    hostname = hostname.lower().rstrip(".")
    for tld, lang in TLD_LANG_MAP.items():
        if hostname.endswith(tld):
            return lang
    return "en"

TR = {
    "en": {
        "report_title": "EU Cyber Resilience Act\nCompliance Report",
        "generated_by": "Generated by Q-CRA Dashboard",
        "target": "Target", "ip": "IP", "tls": "TLS",
        "scan_time": "Scan Time", "report_time": "Report Time",
        "overall_score": "Overall Score", "checks": "Checks",
        "pass": "PASS", "warning": "WARNING", "fail": "FAIL",
        "pqc_ready": "PQC Ready", "yes": "YES", "no": "NO",
        "disclaimer": "This report is auto-generated and provides indicative CRA mapping. It does not constitute legal advice. Consult a qualified notified body for formal assessment.",
        "executive_summary": "1. Executive Summary",
        "cra_article": "CRA Article", "check": "Check", "category": "Category", "status": "Status",
        "detailed_findings": "2. Detailed Findings",
        "remediation": "Remediation",
        "recommendations": "3. Recommendations",
        "priority1": "Priority 1 \u2014 Immediate Action",
        "priority2": "Priority 2 \u2014 Recommended Improvements",
        "pqc_migration": "Post-Quantum Migration",
        "pqc_migration_text": "This infrastructure does not implement post-quantum cryptography. NIST FIPS 203 (ML-KEM) and FIPS 204 (ML-DSA) are finalized. Begin PQC migration planning immediately to protect against harvest-now-decrypt-later attacks. Q-CORE Systems provides migration tooling through Q-HYBRID and Q-MIGRATOR modules.",
        "report_footer": "Report by Q-CRA Dashboard",
        "no_action": "No action",
        "header_report": "CRA COMPLIANCE REPORT",
        "key_exchange_security": "Key Exchange Security",
        "pqc_readiness": "Post-Quantum Cryptography Readiness",
        "tls_protocol": "TLS Protocol Version",
        "cipher_strength": "Cipher Strength",
        "cert_validity": "Certificate Validity",
        "cert_key_quantum": "Certificate Key \u2014 Quantum Resistance",
        "sig_algorithm": "Signature Algorithm \u2014 Quantum Resistance",
        "http_headers": "HTTP Security Headers",
        "hsts_enforcement": "HSTS \u2014 Transport Security Enforcement",
        "deprecated_protocols": "Deprecated Protocol Support",
        "cat_product_security": "Product Security",
        "cat_data_protection": "Data Protection",
        "cat_update_mgmt": "Update Management",
        "cat_security_design": "Security Design",
        "cat_vuln_handling": "Vulnerability Handling",
        "cat_secure_defaults": "Secure Defaults",
        "cat_attack_surface": "Attack Surface",
        "pqc_not_detected": "No PQC algorithms in TLS \u2014 vulnerable to harvest-now-decrypt-later",
        "pqc_detected": "ML-KEM/Kyber detected in TLS handshake",
        "pqc_deploy": "Deploy hybrid PQC key exchange (X25519+ML-KEM-768)",
        "no_deprecated": "No deprecated protocols enabled",
        "hsts_missing": "No HSTS header \u2014 HTTP downgrade possible",
        "hsts_add": "Add Strict-Transport-Security header",
        "all_headers_ok": "All headers present",
        "missing_label": "Missing", "add_label": "Add", "present": "Present",
        "expires_days": "days", "server_negotiated": "Server negotiated",
        "cipher_suite": "Cipher suite", "deprecated_none": "None",
    },
    "cs": {
        "report_title": "EU Cyber Resilience Act\nZpráva o shodě",
        "generated_by": "Vygenerováno Q-CRA Dashboard",
        "target": "Cíl",
        "ip": "IP",
        "tls": "TLS",
        "scan_time": "Čas skenu",
        "report_time": "Čas reportu",
        "overall_score": "Celkové skóre",
        "checks": "Kontrol",
        "pass": "OK",
        "warning": "VAROVÁNÍ",
        "fail": "SELHÁNÍ",
        "pqc_ready": "PQC připravenost",
        "yes": "ANO",
        "no": "NE",
        "disclaimer": "Tato zpráva je generována automaticky a poskytuje orientační mapování na CRA. Nejedná se o právní poradenství. Pro formální posouzení shody kontaktujte notifikovaný orgán.",
        "executive_summary": "1. Shrnutí",
        "cra_article": "Článek CRA",
        "check": "Kontrola",
        "category": "Kategorie",
        "status": "Stav",
        "detailed_findings": "2. Podrobné nálezy",
        "remediation": "Náprava",
        "recommendations": "3. Doporučení",
        "priority1": "Priorita 1 — Okamžitá akce",
        "priority2": "Priorita 2 — Doporučená zlepšení",
        "pqc_migration": "Migrace na post-kvantovou kryptografii",
        "pqc_migration_text": "Tato infrastruktura neimplementuje post-kvantovou kryptografii. Standardy NIST FIPS 203 (ML-KEM) a FIPS 204 (ML-DSA) jsou finalizovány. Zahajte plánování migrace na PQC ihned pro ochranu proti útokům typu harvest-now-decrypt-later. Q-CORE Systems poskytuje nástroje pro migraci prostřednictvím modulů Q-HYBRID a Q-MIGRATOR.",
        "report_footer": "Zpráva vygenerována Q-CRA Dashboard",
        "no_action": "Není třeba akce",
        "header_report": "ZPRÁVA O SHODĚ S CRA",
        "key_exchange_security": "Bezpečnost výměny klíčů",
        "pqc_readiness": "Připravenost na post-kvantovou kryptografii",
        "tls_protocol": "Verze TLS protokolu",
        "cipher_strength": "Síla šifrování",
        "cert_validity": "Platnost certifikátu",
        "cert_key_quantum": "Klíč certifikátu — kvantová odolnost",
        "sig_algorithm": "Podpisový algoritmus — kvantová odolnost",
        "http_headers": "HTTP bezpečnostní hlavičky",
        "hsts_enforcement": "HSTS — vnucení zabezpečeného transportu",
        "deprecated_protocols": "Podpora zastaralých protokolů",
        "cat_product_security": "Bezpečnost produktu",
        "cat_data_protection": "Ochrana dat",
        "cat_update_mgmt": "Správa aktualizací",
        "cat_security_design": "Bezpečnostní návrh",
        "cat_vuln_handling": "Správa zranitelností",
        "cat_secure_defaults": "Bezpečné výchozí nastavení",
        "cat_attack_surface": "Plocha útoku",
        "pqc_not_detected": "Žádné PQC algoritmy v TLS — zranitelné vůči harvest-now-decrypt-later",
        "pqc_detected": "ML-KEM/Kyber detekován v TLS handshake",
        "pqc_deploy": "Nasadit hybridní PQC výměnu klíčů (X25519+ML-KEM-768)",
        "no_deprecated": "Žádné zastaralé protokoly nejsou povoleny",
        "hsts_missing": "Chybí HSTS hlavička — možný downgrade na HTTP",
        "hsts_add": "Přidat Strict-Transport-Security hlavičku",
        "all_headers_ok": "Všechny hlavičky přítomny",
        "missing_label": "Chybí",
        "add_label": "Přidat",
        "present": "Přítomno",
        "expires_days": "dní",
        "server_negotiated": "Server vyjednal",
        "cipher_suite": "Šifrovací sada",
        "deprecated_none": "Žádné",
    },
    "de": {
        "report_title": "EU Cyber Resilience Act\nKonformitätsbericht",
        "generated_by": "Erstellt von Q-CRA Dashboard",
        "target": "Ziel",
        "ip": "IP",
        "tls": "TLS",
        "scan_time": "Scan-Zeit",
        "report_time": "Berichtszeit",
        "overall_score": "Gesamtbewertung",
        "checks": "Prüfungen",
        "pass": "BESTANDEN",
        "warning": "WARNUNG",
        "fail": "FEHLGESCHLAGEN",
        "pqc_ready": "PQC-Bereitschaft",
        "yes": "JA",
        "no": "NEIN",
        "disclaimer": "Dieser Bericht wird automatisch generiert und bietet eine indikative CRA-Zuordnung. Er stellt keine Rechtsberatung dar. Für eine formelle Konformitätsbewertung wenden Sie sich an eine benannte Stelle.",
        "executive_summary": "1. Zusammenfassung",
        "cra_article": "CRA-Artikel",
        "check": "Prüfung",
        "category": "Kategorie",
        "status": "Status",
        "detailed_findings": "2. Detaillierte Ergebnisse",
        "remediation": "Abhilfe",
        "recommendations": "3. Empfehlungen",
        "priority1": "Priorität 1 — Sofortmaßnahmen",
        "priority2": "Priorität 2 — Empfohlene Verbesserungen",
        "pqc_migration": "Post-Quanten-Kryptographie Migration",
        "pqc_migration_text": "Diese Infrastruktur implementiert keine Post-Quanten-Kryptographie. NIST FIPS 203 (ML-KEM) und FIPS 204 (ML-DSA) sind finalisiert. Beginnen Sie sofort mit der PQC-Migrationsplanung zum Schutz gegen Harvest-Now-Decrypt-Later-Angriffe. Q-CORE Systems bietet Migrationswerkzeuge über die Module Q-HYBRID und Q-MIGRATOR.",
        "report_footer": "Bericht erstellt von Q-CRA Dashboard",
        "no_action": "Keine Maßnahme erforderlich",
        "header_report": "CRA-KONFORMITÄTSBERICHT",
        "key_exchange_security": "Schlüsselaustausch-Sicherheit",
        "pqc_readiness": "Post-Quanten-Kryptographie Bereitschaft",
        "tls_protocol": "TLS-Protokollversion",
        "cipher_strength": "Verschlüsselungsstärke",
        "cert_validity": "Zertifikatsgültigkeit",
        "cert_key_quantum": "Zertifikatsschlüssel — Quantenresistenz",
        "sig_algorithm": "Signaturalgorithmus — Quantenresistenz",
        "http_headers": "HTTP-Sicherheitsheader",
        "hsts_enforcement": "HSTS — Transportsicherheit",
        "deprecated_protocols": "Veraltete Protokollunterstützung",
        "cat_product_security": "Produktsicherheit",
        "cat_data_protection": "Datenschutz",
        "cat_update_mgmt": "Update-Management",
        "cat_security_design": "Sicherheitsdesign",
        "cat_vuln_handling": "Schwachstellenmanagement",
        "cat_secure_defaults": "Sichere Standardkonfiguration",
        "cat_attack_surface": "Angriffsfläche",
        "pqc_not_detected": "Keine PQC-Algorithmen in TLS — anfällig für Harvest-Now-Decrypt-Later",
        "pqc_detected": "ML-KEM/Kyber im TLS-Handshake erkannt",
        "pqc_deploy": "Hybriden PQC-Schlüsselaustausch bereitstellen (X25519+ML-KEM-768)",
        "no_deprecated": "Keine veralteten Protokolle aktiviert",
        "hsts_missing": "Kein HSTS-Header — HTTP-Downgrade möglich",
        "hsts_add": "Strict-Transport-Security Header hinzufügen",
        "all_headers_ok": "Alle Header vorhanden",
        "missing_label": "Fehlend",
        "add_label": "Hinzufügen",
        "present": "Vorhanden",
        "expires_days": "Tage",
        "server_negotiated": "Server hat ausgehandelt",
        "cipher_suite": "Cipher-Suite",
        "deprecated_none": "Keine",
    },
}


def t(key: str, lang: str = "en") -> str:
    return TR.get(lang, TR["en"]).get(key, TR["en"].get(key, key))

CAT_KEYS = {
    "Product Security": "cat_product_security",
    "Data Protection": "cat_data_protection",
    "Update Management": "cat_update_mgmt",
    "Security Design": "cat_security_design",
    "Vulnerability Handling": "cat_vuln_handling",
    "Secure Defaults": "cat_secure_defaults",
    "Attack Surface": "cat_attack_surface",
}

TITLE_KEYS = {
    "Key Exchange Security": "key_exchange_security",
    "Post-Quantum Cryptography Readiness": "pqc_readiness",
    "TLS Protocol Version": "tls_protocol",
    "Cipher Strength": "cipher_strength",
    "Certificate Validity": "cert_validity",
    "Certificate Key — Quantum Resistance": "cert_key_quantum",
    "Signature Algorithm — Quantum Resistance": "sig_algorithm",
    "HTTP Security Headers": "http_headers",
    "HSTS — Transport Security Enforcement": "hsts_enforcement",
    "Deprecated Protocol Support": "deprecated_protocols",
}

def translate_result(result: Dict, lang: str) -> Dict:
    r = dict(result)
    tk = TITLE_KEYS.get(r.get("title", ""))
    if tk:
        r["title"] = t(tk, lang)
    ck = CAT_KEYS.get(r.get("category", ""))
    if ck:
        r["category"] = t(ck, lang)
    status_map = {"PASS": t("pass", lang), "WARNING": t("warning", lang), "FAIL": t("fail", lang)}
    r["status_display"] = status_map.get(r.get("status", ""), r.get("status", ""))
    return r


def map_scan_to_cra(scan_data: Dict[str, Any], lang: str = "en") -> List[Dict[str, Any]]:
    results = []
    cipher = scan_data.get("cipher", {})
    certificate = scan_data.get("certificate", {})
    quantum_risks = scan_data.get("quantum_risks", [])
    headers = scan_data.get("http_headers", {})
    protocols = scan_data.get("supported_protocols", [])
    tls_version = scan_data.get("tls_version", "Unknown")

    def find_risk(keyword):
        for r in quantum_risks:
            if keyword.lower() in r.get("component", "").lower():
                return r
        return None

    kex_risk = find_risk("key exchange")
    kex_level = kex_risk.get("level", "UNKNOWN") if kex_risk else "UNKNOWN"
    kex_status = "PASS" if kex_level == "SAFE" else "WARNING" if kex_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({"article": "Art.10(1)", "title": "Key Exchange Security", "category": "Product Security",
        "severity": "CRITICAL", "check": f"Key Exchange: {cipher.get('key_exchange', 'N/A')}",
        "status": kex_status, "detail": kex_risk.get("detail", "") if kex_risk else "",
        "remediation": kex_risk.get("recommendation", "") if kex_risk else "", "nis2": "Art.21(2)(e)"})

    is_pqc = cipher.get("is_pqc", False)
    results.append({"article": "Art.10(5)", "title": "Post-Quantum Cryptography Readiness",
        "category": "Data Protection", "severity": "CRITICAL",
        "check": f"PQC Key Exchange: {'Detected' if is_pqc else 'Not Detected'}",
        "status": "PASS" if is_pqc else "FAIL",
        "detail": t("pqc_detected", lang) if is_pqc else t("pqc_not_detected", lang),
        "remediation": t("no_action", lang) if is_pqc else t("pqc_deploy", lang),
        "nis2": "Art.21(2)(e), Art.21(2)(h)"})

    tls_status = "PASS" if "1.3" in tls_version else "WARNING" if "1.2" in tls_version else "FAIL"
    results.append({"article": "Art.10(1)", "title": "TLS Protocol Version", "category": "Product Security",
        "severity": "HIGH", "check": f"TLS: {tls_version}", "status": tls_status,
        "detail": f"{t('server_negotiated', lang)} {tls_version}",
        "remediation": t("no_action", lang) if tls_status == "PASS" else "Upgrade to TLS 1.3",
        "nis2": "Art.21(2)(e)"})

    enc_bits = cipher.get("encryption_bits", 0)
    enc_status = "PASS" if enc_bits >= 256 else "WARNING" if enc_bits >= 128 else "FAIL"
    results.append({"article": "Art.10(1)", "title": "Cipher Strength", "category": "Product Security",
        "severity": "HIGH", "check": f"{t('cipher_suite', lang)}: {cipher.get('encryption', '')} ({enc_bits}-bit)",
        "status": enc_status, "detail": f"{t('cipher_suite', lang)}: {cipher.get('name', 'N/A')}",
        "remediation": t("no_action", lang) if enc_status == "PASS" else "AES-256-GCM",
        "nis2": "Art.21(2)(e)"})

    cert_expired = certificate.get("is_expired", False)
    days_left = certificate.get("days_until_expiry", -1)
    cert_status = "FAIL" if cert_expired else "WARNING" if days_left < 30 else "PASS"
    results.append({"article": "Art.10(3)", "title": "Certificate Validity", "category": "Update Management",
        "severity": "HIGH", "check": f"{certificate.get('not_after', 'N/A')} ({days_left} {t('expires_days', lang)})",
        "status": cert_status, "detail": f"Subject: {certificate.get('subject', 'N/A')}, Issuer: {certificate.get('issuer', 'N/A')}",
        "remediation": t("no_action", lang) if cert_status == "PASS" else "Renew certificate",
        "nis2": "Art.21(2)(e)"})

    cert_risk = find_risk("certificate key")
    cert_q_level = cert_risk.get("level", "UNKNOWN") if cert_risk else "UNKNOWN"
    cert_q_status = "PASS" if cert_q_level == "SAFE" else "WARNING" if cert_q_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({"article": "Annex I.1", "title": "Certificate Key — Quantum Resistance",
        "category": "Security Design", "severity": "HIGH",
        "check": f"Key: {certificate.get('key_type', 'N/A')} ({certificate.get('key_size', 0)}-bit)",
        "status": cert_q_status, "detail": cert_risk.get("detail", "") if cert_risk else "Unknown",
        "remediation": cert_risk.get("recommendation", "") if cert_risk else "",
        "nis2": "Art.21(2)(e)"})

    sig_risk = find_risk("signature")
    sig_level = sig_risk.get("level", "UNKNOWN") if sig_risk else "UNKNOWN"
    sig_status = "PASS" if sig_level == "SAFE" else "WARNING" if sig_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({"article": "Annex I.2", "title": "Signature Algorithm — Quantum Resistance",
        "category": "Vulnerability Handling", "severity": "MEDIUM",
        "check": f"Signature: {certificate.get('signature_algorithm', 'N/A')}",
        "status": sig_status, "detail": sig_risk.get("detail", "") if sig_risk else "",
        "remediation": sig_risk.get("recommendation", "") if sig_risk else "",
        "nis2": "Art.21(2)(e)"})

    if headers:
        h_score = headers.get("score", 0)
        h_status = "PASS" if h_score >= 80 else "WARNING" if h_score >= 50 else "FAIL"
        missing = headers.get("missing_headers", [])
        results.append({"article": "Art.10(4)", "title": "HTTP Security Headers",
            "category": "Secure Defaults", "severity": "HIGH",
            "check": f"Header Score: {h_score}/100", "status": h_status,
            "detail": f"{t('missing_label', lang)}: {', '.join(missing)}" if missing else t("all_headers_ok", lang),
            "remediation": f"{t('add_label', lang)}: {', '.join(missing)}" if missing else t("no_action", lang),
            "nis2": "Art.21(2)(d)"})

        hsts = headers.get("hsts")
        results.append({"article": "Art.10(6)", "title": "HSTS — Transport Security Enforcement",
            "category": "Attack Surface", "severity": "HIGH",
            "check": f"HSTS: {t('present', lang) if hsts else t('missing_label', lang)}",
            "status": "PASS" if hsts else "FAIL",
            "detail": f"HSTS: {hsts}" if hsts else t("hsts_missing", lang),
            "remediation": t("no_action", lang) if hsts else t("hsts_add", lang),
            "nis2": "Art.21(2)(e)"})

    deprecated_found = [p.get("protocol", "") for p in protocols if p.get("supported") and p.get("status") == "CRITICAL"]
    if protocols:
        results.append({"article": "Art.10(6)", "title": "Deprecated Protocol Support",
            "category": "Attack Surface", "severity": "CRITICAL",
            "check": f"Deprecated: {', '.join(deprecated_found) if deprecated_found else t('deprecated_none', lang)}",
            "status": "FAIL" if deprecated_found else "PASS",
            "detail": f"Server: {', '.join(deprecated_found)}" if deprecated_found else t("no_deprecated", lang),
            "remediation": f"Disable: {', '.join(deprecated_found)}" if deprecated_found else t("no_action", lang),
            "nis2": "Art.21(2)(d)"})

    results = [translate_result(r, lang) for r in results]
    return results


class CRAReportPDF:
    def __init__(self, lang: str = "en"):
        self.lang = lang
        self.styles = getSampleStyleSheet()
        self._add_styles()

    def _add_styles(self):
        self.styles.add(ParagraphStyle("QTitle", parent=self.styles["Title"],
            fontName=_UNICODE_FONT_BOLD, fontSize=24, leading=30, textColor=C_PRIMARY, spaceAfter=4*mm))
        self.styles.add(ParagraphStyle("QH1", parent=self.styles["Heading1"],
            fontName=_UNICODE_FONT_BOLD, fontSize=16, leading=20, textColor=C_PRIMARY, spaceBefore=8*mm, spaceAfter=3*mm))
        self.styles.add(ParagraphStyle("QH2", parent=self.styles["Heading2"],
            fontName=_UNICODE_FONT_BOLD, fontSize=12, leading=16, textColor=C_PRIMARY, spaceBefore=5*mm, spaceAfter=2*mm))
        self.styles.add(ParagraphStyle("QBody", parent=self.styles["Normal"],
            fontName=_UNICODE_FONT, fontSize=9, leading=13, textColor=C_TEXT, alignment=TA_JUSTIFY, spaceAfter=2*mm))
        self.styles.add(ParagraphStyle("QSmall", parent=self.styles["Normal"],
            fontName=_UNICODE_FONT, fontSize=7, leading=9, textColor=C_DIM))

    def _header_footer(self, c, doc):
        c.saveState()
        w, h = A4
        c.setStrokeColor(C_ACCENT); c.setLineWidth(2)
        c.line(20*mm, h-18*mm, w-20*mm, h-18*mm)
        c.setFont(_UNICODE_FONT_BOLD, 7); c.setFillColor(C_PRIMARY)
        c.drawString(20*mm, h-15*mm, f"{COMPANY} | Q-CRA Dashboard v{VERSION}")
        c.setFont(_UNICODE_FONT, 7); c.setFillColor(C_DIM)
        c.drawRightString(w-20*mm, h-15*mm, t("header_report", self.lang))
        c.setStrokeColor(C_NEUTRAL); c.setLineWidth(0.5)
        c.line(20*mm, 15*mm, w-20*mm, 15*mm)
        c.drawString(20*mm, 10*mm, f"{WEBSITE} | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        c.drawRightString(w-20*mm, 10*mm, f"Page {doc.page}")
        c.restoreState()

    def _sc(self, status):
        return {"PASS": C_SUCCESS, "WARNING": C_WARNING, "FAIL": C_DANGER}.get(status, C_NEUTRAL)

    def generate(self, scan_data: Dict, cra_results: List[Dict], output_path: str) -> str:
        lang = self.lang
        doc = SimpleDocTemplate(output_path, pagesize=A4,
            leftMargin=20*mm, rightMargin=20*mm, topMargin=22*mm, bottomMargin=20*mm,
            title=f"CRA Report - {scan_data.get('hostname', 'Unknown')}", author=COMPANY)
        el = []

        _s = self.styles["QBody"]
        _sb = ParagraphStyle("CB", parent=_s, fontName=_UNICODE_FONT_BOLD)
        _sn = ParagraphStyle("CN", parent=_s, fontName=_UNICODE_FONT)

        def P(text, bold=False):
            return Paragraph(str(text), _sb if bold else _sn)

        # Cover
        el.append(Spacer(1, 25*mm))
        el.append(Paragraph(t("report_title", lang).replace("\n", "<br/>"), self.styles["QTitle"]))
        el.append(Paragraph(f"{t('generated_by', lang)} v{VERSION} | {COMPANY}", self.styles["QSmall"]))
        el.append(Spacer(1, 10*mm))

        total = len(cra_results)
        passes = sum(1 for r in cra_results if r["status"] == "PASS")
        warnings = sum(1 for r in cra_results if r["status"] == "WARNING")
        fails = sum(1 for r in cra_results if r["status"] == "FAIL")
        score = round((passes / total) * 100) if total else 0
        pqc = scan_data.get("cipher", {}).get("is_pqc", False)

        info = [
            [P(f"{t('target', lang)}:", True), P(scan_data.get("hostname", "N/A"))],
            [P(f"{t('ip', lang)}:", True), P(scan_data.get("ip_address", "N/A"))],
            [P(f"{t('tls', lang)}:", True), P(scan_data.get("tls_version", "N/A"))],
            [P(f"{t('scan_time', lang)}:", True), P(scan_data.get("scan_timestamp", "N/A"))],
            [P(f"{t('report_time', lang)}:", True), P(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))],
            [P(""), P("")],
            [P(f"{t('overall_score', lang)}:", True), P(f"{score}%")],
            [P(f"{t('checks', lang)}:", True), P(str(total))],
            [P(f"{t('pass', lang)}:", True), P(str(passes))],
            [P(f"{t('warning', lang)}:", True), P(str(warnings))],
            [P(f"{t('fail', lang)}:", True), P(str(fails))],
            [P(f"{t('pqc_ready', lang)}:", True), P(t("yes", lang) if pqc else t("no", lang))],
        ]
        tb = Table(info, colWidths=[40*mm, 110*mm])
        tb.setStyle(TableStyle([
            ("BOTTOMPADDING", (0,0), (-1,-1), 3), ("TOPPADDING", (0,0), (-1,-1), 3),
            ("LINEBELOW", (0,5), (-1,5), 0.5, C_NEUTRAL),
            ("BACKGROUND", (0,6), (-1,6), C_BG), ("VALIGN", (0,0), (-1,-1), "TOP"),
        ]))
        el.append(tb)
        el.append(Spacer(1, 8*mm))
        el.append(Paragraph(f"<b>Disclaimer:</b> {t('disclaimer', lang)}", self.styles["QSmall"]))
        el.append(PageBreak())

        # Executive Summary
        el.append(Paragraph(t("executive_summary", lang), self.styles["QH1"]))
        _sh = ParagraphStyle("HC", parent=_sn, textColor=white, fontName=_UNICODE_FONT_BOLD, fontSize=8)
        _st = ParagraphStyle("TC", parent=_sn, fontSize=8)
        _stb = ParagraphStyle("TCB", parent=_sb, fontSize=8)

        hdr = [Paragraph(t("cra_article", lang), _sh), Paragraph(t("check", lang), _sh),
               Paragraph(t("category", lang), _sh), Paragraph(t("status", lang), _sh)]
        td = [hdr]
        for r in cra_results:
            sc = self._sc(r["status"])
            ss = ParagraphStyle("SS", parent=_stb, textColor=sc, alignment=1)
            td.append([Paragraph(r["article"], _st), Paragraph(r["title"], _st),
                       Paragraph(r["category"], _st), Paragraph(r.get("status_display", r["status"]), ss)])
        et = Table(td, colWidths=[25*mm, 55*mm, 40*mm, 25*mm])
        et.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), C_PRIMARY),
            ("GRID", (0,0), (-1,-1), 0.4, C_NEUTRAL),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [white, C_BG]),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4), ("TOPPADDING", (0,0), (-1,-1), 4),
            ("VALIGN", (0,0), (-1,-1), "TOP"),
        ]))
        el.append(et)
        el.append(PageBreak())

        # Detailed Findings
        el.append(Paragraph(t("detailed_findings", lang), self.styles["QH1"]))
        for r in cra_results:
            cl = self._sc(r["status"])
            bl = []
            bl.append(Paragraph(
                f'<font color="{cl.hexval()}">[{r.get("status_display", r["status"])}]</font> '
                f'{r["article"]} \u2014 {r["title"]}',
                ParagraphStyle("FT", parent=self.styles["Normal"],
                    fontSize=10, fontName=_UNICODE_FONT_BOLD, textColor=C_PRIMARY, spaceAfter=1*mm)))
            bl.append(Paragraph(f'<b>{t("check", lang)}:</b> {r["check"]}', self.styles["QBody"]))
            if r.get("detail"):
                bl.append(Paragraph(f'<i>{r["detail"]}</i>', self.styles["QBody"]))
            if r.get("remediation") and r["remediation"] != t("no_action", lang):
                bl.append(Paragraph(f'<b>{t("remediation", lang)}:</b> {r["remediation"]}', self.styles["QBody"]))
            bl.append(Paragraph(f'<b>CRA:</b> {r["article"]} | <b>NIS2:</b> {r.get("nis2", "N/A")}', self.styles["QBody"]))
            bl.append(Spacer(1, 4*mm))
            el.append(KeepTogether(bl))

        # Recommendations
        el.append(PageBreak())
        el.append(Paragraph(t("recommendations", lang), self.styles["QH1"]))
        fails_list = [r for r in cra_results if r["status"] == "FAIL"]
        warns_list = [r for r in cra_results if r["status"] == "WARNING"]
        if fails_list:
            el.append(Paragraph(t("priority1", lang), self.styles["QH2"]))
            for r in fails_list:
                el.append(Paragraph(f'<b>{r["article"]}</b> \u2014 {r["title"]}: {r.get("remediation", "")}', self.styles["QBody"]))
        if warns_list:
            el.append(Paragraph(t("priority2", lang), self.styles["QH2"]))
            for r in warns_list:
                el.append(Paragraph(f'<b>{r["article"]}</b> \u2014 {r["title"]}: {r.get("remediation", "")}', self.styles["QBody"]))
        if not pqc:
            el.append(Paragraph(t("pqc_migration", lang), self.styles["QH2"]))
            el.append(Paragraph(t("pqc_migration_text", lang), self.styles["QBody"]))

        el.append(Spacer(1, 15*mm))
        el.append(Paragraph(f"{t('report_footer', lang)} v{VERSION} | {COMPANY} | {WEBSITE}", self.styles["QSmall"]))

        doc.build(el, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        return output_path
