"""
Q-CRA Engine — CRA Report Generator for Web (Multilingual)
============================================================
Q-CORE Systems | qcore.systems

Generates CRA compliance PDF in English, Czech, or German.
Language auto-detected from domain TLD or manually selected.
"""

import hashlib
import json
import os
import secrets
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)

VERSION = "2.1.0"
COMPANY = "Q-CORE Systems"
WEBSITE = "qcore.systems"

# Colors
C_PRIMARY = HexColor("#0A1628")
C_ACCENT = HexColor("#00E5FF")
C_SUCCESS = HexColor("#00C853")
C_WARNING = HexColor("#FFB300")
C_DANGER = HexColor("#FF3B5C")
C_NEUTRAL = HexColor("#B0BEC5")
C_BG = HexColor("#F0F4F8")
C_TEXT = HexColor("#1A1A2E")
C_DIM = HexColor("#6B7280")

# ============================================================================
# TLD -> LANGUAGE MAPPING
# ============================================================================
TLD_LANG_MAP = {
    ".cz": "cs", ".sk": "cs",
    ".de": "de", ".at": "de", ".ch": "de",
}

def detect_language(hostname: str) -> str:
    """Detect language from domain TLD."""
    hostname = hostname.lower().rstrip(".")
    for tld, lang in TLD_LANG_MAP.items():
        if hostname.endswith(tld):
            return lang
    return "en"

# ============================================================================
# TRANSLATIONS
# ============================================================================
TR = {
    "en": {
        "report_title": "EU Cyber Resilience Act\nCompliance Report",
        "generated_by": "Generated by Q-CRA Dashboard",
        "target": "Target",
        "ip": "IP",
        "tls": "TLS",
        "scan_time": "Scan Time",
        "report_time": "Report Time",
        "overall_score": "Overall Score",
        "checks": "Checks",
        "pass": "PASS",
        "warning": "WARNING",
        "fail": "FAIL",
        "pqc_ready": "PQC Ready",
        "yes": "YES",
        "no": "NO",
        "disclaimer": "This report is auto-generated and provides indicative CRA mapping. "
                      "It does not constitute legal advice. Consult a qualified notified body for formal assessment.",
        "executive_summary": "1. Executive Summary",
        "cra_article": "CRA Article",
        "check": "Check",
        "category": "Category",
        "status": "Status",
        "detailed_findings": "2. Detailed Findings",
        "remediation": "Remediation",
        "recommendations": "3. Recommendations",
        "priority1": "Priority 1 — Immediate Action",
        "priority2": "Priority 2 — Recommended Improvements",
        "pqc_migration": "Post-Quantum Migration",
        "pqc_migration_text": "This infrastructure does not implement post-quantum cryptography. "
                              "NIST FIPS 203 (ML-KEM) and FIPS 204 (ML-DSA) are finalized. "
                              "Begin PQC migration planning immediately to protect against "
                              "harvest-now-decrypt-later attacks. Q-CORE Systems provides "
                              "migration tooling through Q-HYBRID and Q-MIGRATOR modules.",
        "report_footer": "Report by Q-CRA Dashboard",
        "no_action": "No action",
        "header_report": "CRA COMPLIANCE REPORT",
        # CRA check titles
        "key_exchange_security": "Key Exchange Security",
        "pqc_readiness": "Post-Quantum Cryptography Readiness",
        "tls_protocol": "TLS Protocol Version",
        "cipher_strength": "Cipher Strength",
        "cert_validity": "Certificate Validity",
        "cert_key_quantum": "Certificate Key — Quantum Resistance",
        "sig_algorithm": "Signature Algorithm — Quantum Resistance",
        "http_headers": "HTTP Security Headers",
        "hsts_enforcement": "HSTS — Transport Security Enforcement",
        "deprecated_protocols": "Deprecated Protocol Support",
        # Categories
        "cat_product_security": "Product Security",
        "cat_data_protection": "Data Protection",
        "cat_update_mgmt": "Update Management",
        "cat_security_design": "Security Design",
        "cat_vuln_handling": "Vulnerability Handling",
        "cat_secure_defaults": "Secure Defaults",
        "cat_attack_surface": "Attack Surface",
        # Findings details
        "pqc_not_detected": "No PQC algorithms in TLS — vulnerable to harvest-now-decrypt-later",
        "pqc_detected": "ML-KEM/Kyber detected in TLS handshake",
        "pqc_deploy": "Deploy hybrid PQC key exchange (X25519+ML-KEM-768)",
        "no_deprecated": "No deprecated protocols enabled",
        "hsts_missing": "No HSTS header — HTTP downgrade possible",
        "hsts_add": "Add Strict-Transport-Security header",
        "all_headers_ok": "All headers present",
        "missing_label": "Missing",
        "add_label": "Add",
        "present": "Present",
        "expires_days": "days",
        "server_negotiated": "Server negotiated",
        "cipher_suite": "Cipher suite",
        "deprecated_none": "None",
    },
    "cs": {
        "report_title": "EU Cyber Resilience Act\nZpr\u00e1va o shod\u011b",
        "generated_by": "Vygenerov\u00e1no Q-CRA Dashboard",
        "target": "C\u00edl",
        "ip": "IP",
        "tls": "TLS",
        "scan_time": "\u010cas skenu",
        "report_time": "\u010cas reportu",
        "overall_score": "Celkov\u00e9 sk\u00f3re",
        "checks": "Kontrol",
        "pass": "OK",
        "warning": "VAROV\u00c1N\u00cd",
        "fail": "SELH\u00c1N\u00cd",
        "pqc_ready": "PQC p\u0159ipravenost",
        "yes": "ANO",
        "no": "NE",
        "disclaimer": "Tato zpr\u00e1va je generov\u00e1na automaticky a poskytuje orientan\u010dn\u00ed mapov\u00e1n\u00ed na CRA. "
                      "Nejedn\u00e1 se o pr\u00e1vn\u00ed poradenstv\u00ed. Pro form\u00e1ln\u00ed posouzen\u00ed shody kontaktujte notifikovan\u00fd org\u00e1n.",
        "executive_summary": "1. Shrnut\u00ed",
        "cra_article": "\u010cl\u00e1nek CRA",
        "check": "Kontrola",
        "category": "Kategorie",
        "status": "Stav",
        "detailed_findings": "2. Podrobn\u00e9 n\u00e1lezy",
        "remediation": "N\u00e1prava",
        "recommendations": "3. Doporu\u010den\u00ed",
        "priority1": "Priorita 1 — Okam\u017eit\u00e1 akce",
        "priority2": "Priorita 2 — Doporu\u010den\u00e1 zlep\u0161en\u00ed",
        "pqc_migration": "Migrace na post-kvantovou kryptografii",
        "pqc_migration_text": "Tato infrastruktura neimplementuje post-kvantovou kryptografii. "
                              "Standardy NIST FIPS 203 (ML-KEM) a FIPS 204 (ML-DSA) jsou finalizov\u00e1ny. "
                              "Zahajte pl\u00e1nov\u00e1n\u00ed migrace na PQC ihned pro ochranu proti \u00fatok\u016fm "
                              "typu harvest-now-decrypt-later. Q-CORE Systems poskytuje n\u00e1stroje "
                              "pro migraci prost\u0159ednictv\u00edm modul\u016f Q-HYBRID a Q-MIGRATOR.",
        "report_footer": "Zpr\u00e1va vygenerov\u00e1na Q-CRA Dashboard",
        "no_action": "Nen\u00ed t\u0159eba akce",
        "header_report": "ZPR\u00c1VA O SHOD\u011a S CRA",
        "key_exchange_security": "Bezpe\u010dnost v\u00fdm\u011bny kl\u00ed\u010d\u016f",
        "pqc_readiness": "P\u0159ipravenost na post-kvantovou kryptografii",
        "tls_protocol": "Verze TLS protokolu",
        "cipher_strength": "S\u00edla \u0161ifrov\u00e1n\u00ed",
        "cert_validity": "Platnost certifik\u00e1tu",
        "cert_key_quantum": "Kl\u00ed\u010d certifik\u00e1tu — kvantov\u00e1 odolnost",
        "sig_algorithm": "Podpisov\u00fd algoritmus — kvantov\u00e1 odolnost",
        "http_headers": "HTTP bezpe\u010dnostn\u00ed hlavi\u010dky",
        "hsts_enforcement": "HSTS — vynucen\u00ed zabezpe\u010den\u00e9ho transportu",
        "deprecated_protocols": "Podpora zastaral\u00fdch protokol\u016f",
        "cat_product_security": "Bezpe\u010dnost produktu",
        "cat_data_protection": "Ochrana dat",
        "cat_update_mgmt": "Spr\u00e1va aktualizac\u00ed",
        "cat_security_design": "Bezpe\u010dnostn\u00ed n\u00e1vrh",
        "cat_vuln_handling": "Spr\u00e1va zranitelnost\u00ed",
        "cat_secure_defaults": "Bezpe\u010dn\u00e9 v\u00fdchoz\u00ed nastaven\u00ed",
        "cat_attack_surface": "Plocha \u00fatoku",
        "pqc_not_detected": "\u017d\u00e1dn\u00e9 PQC algoritmy v TLS — zraniteln\u00e9 v\u016f\u010di harvest-now-decrypt-later",
        "pqc_detected": "ML-KEM/Kyber detekovan v TLS handshake",
        "pqc_deploy": "Nasadit hybridn\u00ed PQC v\u00fdm\u011bnu kl\u00ed\u010d\u016f (X25519+ML-KEM-768)",
        "no_deprecated": "\u017d\u00e1dn\u00e9 zastaral\u00e9 protokoly nejsou povoleny",
        "hsts_missing": "Chyb\u00ed HSTS hlavi\u010dka — mo\u017en\u00fd downgrade na HTTP",
        "hsts_add": "P\u0159idat Strict-Transport-Security hlavi\u010dku",
        "all_headers_ok": "V\u0161echny hlavi\u010dky p\u0159\u00edtomny",
        "missing_label": "Chyb\u00ed",
        "add_label": "P\u0159idat",
        "present": "P\u0159\u00edtomno",
        "expires_days": "dn\u00ed",
        "server_negotiated": "Server vyjednal",
        "cipher_suite": "\u0160ifrovac\u00ed sada",
        "deprecated_none": "\u017d\u00e1dn\u00e9",
    },
    "de": {
        "report_title": "EU Cyber Resilience Act\nKonformit\u00e4tsbericht",
        "generated_by": "Erstellt von Q-CRA Dashboard",
        "target": "Ziel",
        "ip": "IP",
        "tls": "TLS",
        "scan_time": "Scan-Zeit",
        "report_time": "Berichtszeit",
        "overall_score": "Gesamtbewertung",
        "checks": "Pr\u00fcfungen",
        "pass": "BESTANDEN",
        "warning": "WARNUNG",
        "fail": "FEHLGESCHLAGEN",
        "pqc_ready": "PQC-Bereitschaft",
        "yes": "JA",
        "no": "NEIN",
        "disclaimer": "Dieser Bericht wird automatisch generiert und bietet eine indikative CRA-Zuordnung. "
                      "Er stellt keine Rechtsberatung dar. F\u00fcr eine formelle Konformit\u00e4tsbewertung "
                      "wenden Sie sich an eine benannte Stelle.",
        "executive_summary": "1. Zusammenfassung",
        "cra_article": "CRA-Artikel",
        "check": "Pr\u00fcfung",
        "category": "Kategorie",
        "status": "Status",
        "detailed_findings": "2. Detaillierte Ergebnisse",
        "remediation": "Abhilfe",
        "recommendations": "3. Empfehlungen",
        "priority1": "Priorit\u00e4t 1 — Sofortma\u00dfnahmen",
        "priority2": "Priorit\u00e4t 2 — Empfohlene Verbesserungen",
        "pqc_migration": "Post-Quanten-Kryptographie Migration",
        "pqc_migration_text": "Diese Infrastruktur implementiert keine Post-Quanten-Kryptographie. "
                              "NIST FIPS 203 (ML-KEM) und FIPS 204 (ML-DSA) sind finalisiert. "
                              "Beginnen Sie sofort mit der PQC-Migrationsplanung zum Schutz gegen "
                              "Harvest-Now-Decrypt-Later-Angriffe. Q-CORE Systems bietet "
                              "Migrationswerkzeuge \u00fcber die Module Q-HYBRID und Q-MIGRATOR.",
        "report_footer": "Bericht erstellt von Q-CRA Dashboard",
        "no_action": "Keine Ma\u00dfnahme erforderlich",
        "header_report": "CRA-KONFORMIT\u00c4TSBERICHT",
        "key_exchange_security": "Schl\u00fcsselaustausch-Sicherheit",
        "pqc_readiness": "Post-Quanten-Kryptographie Bereitschaft",
        "tls_protocol": "TLS-Protokollversion",
        "cipher_strength": "Verschl\u00fcsselungsst\u00e4rke",
        "cert_validity": "Zertifikatsg\u00fcltigkeit",
        "cert_key_quantum": "Zertifikatsschl\u00fcssel — Quantenresistenz",
        "sig_algorithm": "Signaturalgorithmus — Quantenresistenz",
        "http_headers": "HTTP-Sicherheitsheader",
        "hsts_enforcement": "HSTS — Transportsicherheit",
        "deprecated_protocols": "Veraltete Protokollunterst\u00fctzung",
        "cat_product_security": "Produktsicherheit",
        "cat_data_protection": "Datenschutz",
        "cat_update_mgmt": "Update-Management",
        "cat_security_design": "Sicherheitsdesign",
        "cat_vuln_handling": "Schwachstellenmanagement",
        "cat_secure_defaults": "Sichere Standardkonfiguration",
        "cat_attack_surface": "Angriffsfl\u00e4che",
        "pqc_not_detected": "Keine PQC-Algorithmen in TLS — anf\u00e4llig f\u00fcr Harvest-Now-Decrypt-Later",
        "pqc_detected": "ML-KEM/Kyber im TLS-Handshake erkannt",
        "pqc_deploy": "Hybriden PQC-Schl\u00fcsselaustausch bereitstellen (X25519+ML-KEM-768)",
        "no_deprecated": "Keine veralteten Protokolle aktiviert",
        "hsts_missing": "Kein HSTS-Header — HTTP-Downgrade m\u00f6glich",
        "hsts_add": "Strict-Transport-Security Header hinzuf\u00fcgen",
        "all_headers_ok": "Alle Header vorhanden",
        "missing_label": "Fehlend",
        "add_label": "Hinzuf\u00fcgen",
        "present": "Vorhanden",
        "expires_days": "Tage",
        "server_negotiated": "Server hat ausgehandelt",
        "cipher_suite": "Cipher-Suite",
        "deprecated_none": "Keine",
    },
}

def t(key: str, lang: str = "en") -> str:
    """Get translation."""
    return TR.get(lang, TR["en"]).get(key, TR["en"].get(key, key))

# Category translation helper
CAT_KEYS = {
    "Product Security": "cat_product_security",
    "Data Protection": "cat_data_protection",
    "Update Management": "cat_update_mgmt",
    "Security Design": "cat_security_design",
    "Vulnerability Handling": "cat_vuln_handling",
    "Secure Defaults": "cat_secure_defaults",
    "Attack Surface": "cat_attack_surface",
}

TITLE_KEYS = {
    "Key Exchange Security": "key_exchange_security",
    "Post-Quantum Cryptography Readiness": "pqc_readiness",
    "TLS Protocol Version": "tls_protocol",
    "Cipher Strength": "cipher_strength",
    "Certificate Validity": "cert_validity",
    "Certificate Key — Quantum Resistance": "cert_key_quantum",
    "Signature Algorithm — Quantum Resistance": "sig_algorithm",
    "HTTP Security Headers": "http_headers",
    "HSTS — Transport Security Enforcement": "hsts_enforcement",
    "Deprecated Protocol Support": "deprecated_protocols",
}

def translate_result(result: Dict, lang: str) -> Dict:
    """Translate a single CRA result dict."""
    r = dict(result)
    # Translate title
    tk = TITLE_KEYS.get(r.get("title", ""))
    if tk:
        r["title"] = t(tk, lang)
    # Translate category
    ck = CAT_KEYS.get(r.get("category", ""))
    if ck:
        r["category"] = t(ck, lang)
    # Translate status
    status_map = {"PASS": t("pass", lang), "WARNING": t("warning", lang), "FAIL": t("fail", lang)}
    r["status_display"] = status_map.get(r.get("status", ""), r.get("status", ""))
    # Keep original status for coloring
    return r


# ============================================================================
# CRA MAPPING (language-independent logic)
# ============================================================================
def map_scan_to_cra(scan_data: Dict[str, Any], lang: str = "en") -> List[Dict[str, Any]]:
    """Map web scanner results to CRA articles."""
    results = []

    cipher = scan_data.get("cipher", {})
    certificate = scan_data.get("certificate", {})
    quantum_risks = scan_data.get("quantum_risks", [])
    headers = scan_data.get("http_headers", {})
    protocols = scan_data.get("supported_protocols", [])
    tls_version = scan_data.get("tls_version", "Unknown")

    def find_risk(keyword):
        for r in quantum_risks:
            if keyword.lower() in r.get("component", "").lower():
                return r
        return None

    # 1. Key Exchange
    kex_risk = find_risk("key exchange")
    kex_level = kex_risk.get("level", "UNKNOWN") if kex_risk else "UNKNOWN"
    kex_status = "PASS" if kex_level == "SAFE" else "WARNING" if kex_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({
        "article": "Art.10(1)",
        "title": "Key Exchange Security",
        "category": "Product Security",
        "severity": "CRITICAL",
        "check": f"Key Exchange: {cipher.get('key_exchange', 'N/A')}",
        "status": kex_status,
        "detail": kex_risk.get("detail", "") if kex_risk else "",
        "remediation": kex_risk.get("recommendation", "") if kex_risk else "",
        "nis2": "Art.21(2)(e)",
    })

    # 2. PQC Readiness
    is_pqc = cipher.get("is_pqc", False)
    results.append({
        "article": "Art.10(5)",
        "title": "Post-Quantum Cryptography Readiness",
        "category": "Data Protection",
        "severity": "CRITICAL",
        "check": f"PQC Key Exchange: {'Detected' if is_pqc else 'Not Detected'}",
        "status": "PASS" if is_pqc else "FAIL",
        "detail": t("pqc_detected", lang) if is_pqc else t("pqc_not_detected", lang),
        "remediation": t("no_action", lang) if is_pqc else t("pqc_deploy", lang),
        "nis2": "Art.21(2)(e), Art.21(2)(h)",
    })

    # 3. TLS Version
    tls_status = "PASS" if "1.3" in tls_version else "WARNING" if "1.2" in tls_version else "FAIL"
    results.append({
        "article": "Art.10(1)",
        "title": "TLS Protocol Version",
        "category": "Product Security",
        "severity": "HIGH",
        "check": f"TLS: {tls_version}",
        "status": tls_status,
        "detail": f"{t('server_negotiated', lang)} {tls_version}",
        "remediation": t("no_action", lang) if tls_status == "PASS" else "Upgrade to TLS 1.3",
        "nis2": "Art.21(2)(e)",
    })

    # 4. Cipher Strength
    enc = cipher.get("encryption", "")
    enc_bits = cipher.get("encryption_bits", 0)
    enc_status = "PASS" if enc_bits >= 256 else "WARNING" if enc_bits >= 128 else "FAIL"
    results.append({
        "article": "Art.10(1)",
        "title": "Cipher Strength",
        "category": "Product Security",
        "severity": "HIGH",
        "check": f"{t('cipher_suite', lang)}: {enc} ({enc_bits}-bit)",
        "status": enc_status,
        "detail": f"{t('cipher_suite', lang)}: {cipher.get('name', 'N/A')}",
        "remediation": t("no_action", lang) if enc_status == "PASS" else "AES-256-GCM",
        "nis2": "Art.21(2)(e)",
    })

    # 5. Certificate
    cert_expired = certificate.get("is_expired", False)
    days_left = certificate.get("days_until_expiry", -1)
    cert_status = "FAIL" if cert_expired else "WARNING" if days_left < 30 else "PASS"
    results.append({
        "article": "Art.10(3)",
        "title": "Certificate Validity",
        "category": "Update Management",
        "severity": "HIGH",
        "check": f"{certificate.get('not_after', 'N/A')} ({days_left} {t('expires_days', lang)})",
        "status": cert_status,
        "detail": f"Subject: {certificate.get('subject', 'N/A')}, Issuer: {certificate.get('issuer', 'N/A')}",
        "remediation": t("no_action", lang) if cert_status == "PASS" else "Renew certificate",
        "nis2": "Art.21(2)(e)",
    })

    # 6. Certificate Key Quantum Risk
    cert_risk = find_risk("certificate key")
    cert_q_level = cert_risk.get("level", "UNKNOWN") if cert_risk else "UNKNOWN"
    cert_q_status = "PASS" if cert_q_level == "SAFE" else "WARNING" if cert_q_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({
        "article": "Annex I.1",
        "title": "Certificate Key — Quantum Resistance",
        "category": "Security Design",
        "severity": "HIGH",
        "check": f"Key: {certificate.get('key_type', 'N/A')} ({certificate.get('key_size', 0)}-bit)",
        "status": cert_q_status,
        "detail": cert_risk.get("detail", "") if cert_risk else "Unknown",
        "remediation": cert_risk.get("recommendation", "") if cert_risk else "",
        "nis2": "Art.21(2)(e)",
    })

    # 7. Signature Algorithm
    sig_risk = find_risk("signature")
    sig_level = sig_risk.get("level", "UNKNOWN") if sig_risk else "UNKNOWN"
    sig_status = "PASS" if sig_level == "SAFE" else "WARNING" if sig_level in ("LOW", "MEDIUM") else "FAIL"
    results.append({
        "article": "Annex I.2",
        "title": "Signature Algorithm — Quantum Resistance",
        "category": "Vulnerability Handling",
        "severity": "MEDIUM",
        "check": f"Signature: {certificate.get('signature_algorithm', 'N/A')}",
        "status": sig_status,
        "detail": sig_risk.get("detail", "") if sig_risk else "",
        "remediation": sig_risk.get("recommendation", "") if sig_risk else "",
        "nis2": "Art.21(2)(e)",
    })

    # 8. Security Headers
    if headers:
        h_score = headers.get("score", 0)
        h_status = "PASS" if h_score >= 80 else "WARNING" if h_score >= 50 else "FAIL"
        missing = headers.get("missing_headers", [])
        results.append({
            "article": "Art.10(4)",
            "title": "HTTP Security Headers",
            "category": "Secure Defaults",
            "severity": "HIGH",
            "check": f"Header Score: {h_score}/100",
            "status": h_status,
            "detail": f"{t('missing_label', lang)}: {', '.join(missing)}" if missing else t("all_headers_ok", lang),
            "remediation": f"{t('add_label', lang)}: {', '.join(missing)}" if missing else t("no_action", lang),
            "nis2": "Art.21(2)(d)",
        })

        # 9. HSTS
        hsts = headers.get("hsts")
        results.append({
            "article": "Art.10(6)",
            "title": "HSTS — Transport Security Enforcement",
            "category": "Attack Surface",
            "severity": "HIGH",
            "check": f"HSTS: {t('present', lang) if hsts else t('missing_label', lang)}",
            "status": "PASS" if hsts else "FAIL",
            "detail": f"HSTS: {hsts}" if hsts else t("hsts_missing", lang),
            "remediation": t("no_action", lang) if hsts else t("hsts_add", lang),
            "nis2": "Art.21(2)(e)",
        })

    # 10. Deprecated protocols
    deprecated_found = []
    for p in protocols:
        if p.get("supported") and p.get("status") == "CRITICAL":
            deprecated_found.append(p.get("protocol", ""))
    if protocols:
        results.append({
            "article": "Art.10(6)",
            "title": "Deprecated Protocol Support",
            "category": "Attack Surface",
            "severity": "CRITICAL",
            "check": f"Deprecated: {', '.join(deprecated_found) if deprecated_found else t('deprecated_none', lang)}",
            "status": "FAIL" if deprecated_found else "PASS",
            "detail": f"Server: {', '.join(deprecated_found)}" if deprecated_found else t("no_deprecated", lang),
            "remediation": f"Disable: {', '.join(deprecated_found)}" if deprecated_found else t("no_action", lang),
            "nis2": "Art.21(2)(d)",
        })

    # Translate all results
    results = [translate_result(r, lang) for r in results]
    return results


# ============================================================================
# PDF GENERATOR (Multilingual)
# ============================================================================
class CRAReportPDF:
    """Generate CRA compliance PDF with language support."""

    def __init__(self, lang: str = "en"):
        self.lang = lang
        self.styles = getSampleStyleSheet()
        self._add_styles()

    def _add_styles(self):
        self.styles.add(ParagraphStyle("QTitle", parent=self.styles["Title"],
            fontSize=24, leading=30, textColor=C_PRIMARY, spaceAfter=4*mm))
        self.styles.add(ParagraphStyle("QH1", parent=self.styles["Heading1"],
            fontSize=16, leading=20, textColor=C_PRIMARY, spaceBefore=8*mm, spaceAfter=3*mm))
        self.styles.add(ParagraphStyle("QH2", parent=self.styles["Heading2"],
            fontSize=12, leading=16, textColor=C_PRIMARY, spaceBefore=5*mm, spaceAfter=2*mm))
        self.styles.add(ParagraphStyle("QBody", parent=self.styles["Normal"],
            fontSize=9, leading=13, textColor=C_TEXT, alignment=TA_JUSTIFY, spaceAfter=2*mm))
        self.styles.add(ParagraphStyle("QSmall", parent=self.styles["Normal"],
            fontSize=7, leading=9, textColor=C_DIM))

    def _header_footer(self, c, doc):
        c.saveState()
        w, h = A4
        c.setStrokeColor(C_ACCENT); c.setLineWidth(2)
        c.line(20*mm, h-18*mm, w-20*mm, h-18*mm)
        c.setFont("Helvetica-Bold", 7); c.setFillColor(C_PRIMARY)
        c.drawString(20*mm, h-15*mm, f"{COMPANY} | Q-CRA Dashboard v{VERSION}")
        c.setFont("Helvetica", 7); c.setFillColor(C_DIM)
        c.drawRightString(w-20*mm, h-15*mm, t("header_report", self.lang))
        c.setStrokeColor(C_NEUTRAL); c.setLineWidth(0.5)
        c.line(20*mm, 15*mm, w-20*mm, 15*mm)
        c.drawString(20*mm, 10*mm, f"{WEBSITE} | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        c.drawRightString(w-20*mm, 10*mm, f"Page {doc.page}")
        c.restoreState()

    def _sc(self, status):
        return {"PASS": C_SUCCESS, "WARNING": C_WARNING, "FAIL": C_DANGER}.get(status, C_NEUTRAL)

    def generate(self, scan_data: Dict, cra_results: List[Dict], output_path: str) -> str:
        lang = self.lang
        doc = SimpleDocTemplate(output_path, pagesize=A4,
            leftMargin=20*mm, rightMargin=20*mm, topMargin=22*mm, bottomMargin=20*mm,
            title=f"CRA Report — {scan_data.get('hostname', 'Unknown')}",
            author=COMPANY)

        el = []

        # Cover
        el.append(Spacer(1, 25*mm))
        el.append(Paragraph(t("report_title", lang).replace("\n", "<br/>"), self.styles["QTitle"]))
        el.append(Paragraph(f"{t('generated_by', lang)} v{VERSION} | {COMPANY}", self.styles["QSmall"]))
        el.append(Spacer(1, 10*mm))

        total = len(cra_results)
        passes = sum(1 for r in cra_results if r["status"] == "PASS")
        warnings = sum(1 for r in cra_results if r["status"] == "WARNING")
        fails = sum(1 for r in cra_results if r["status"] == "FAIL")
        score = round((passes / total) * 100) if total else 0
        pqc = scan_data.get("cipher", {}).get("is_pqc", False)

        info = [
            [f"{t('target', lang)}:", scan_data.get("hostname", "N/A")],
            [f"{t('ip', lang)}:", scan_data.get("ip_address", "N/A")],
            [f"{t('tls', lang)}:", scan_data.get("tls_version", "N/A")],
            [f"{t('scan_time', lang)}:", scan_data.get("scan_timestamp", "N/A")],
            [f"{t('report_time', lang)}:", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
            ["", ""],
            [f"{t('overall_score', lang)}:", f"{score}%"],
            [f"{t('checks', lang)}:", str(total)],
            [t("pass", lang) + ":", str(passes)],
            [t("warning", lang) + ":", str(warnings)],
            [t("fail", lang) + ":", str(fails)],
            [f"{t('pqc_ready', lang)}:", t("yes", lang) if pqc else t("no", lang)],
        ]
        tb = Table(info, colWidths=[40*mm, 110*mm])
        tb.setStyle(TableStyle([
            ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("TEXTCOLOR", (0,0), (0,-1), C_PRIMARY),
            ("BOTTOMPADDING", (0,0), (-1,-1), 3),
            ("LINEBELOW", (0,5), (-1,5), 0.5, C_NEUTRAL),
            ("BACKGROUND", (0,6), (-1,6), C_BG),
        ]))
        el.append(tb)
        el.append(Spacer(1, 8*mm))
        el.append(Paragraph(f"<b>Disclaimer:</b> {t('disclaimer', lang)}", self.styles["QSmall"]))
        el.append(PageBreak())

        # Executive Summary
        el.append(Paragraph(t("executive_summary", lang), self.styles["QH1"]))
        hdr = [t("cra_article", lang), t("check", lang), t("category", lang), t("status", lang)]
        td = [hdr]
        for r in cra_results:
            td.append([r["article"], r["title"], r["category"], r.get("status_display", r["status"])])
        et = Table(td, colWidths=[25*mm, 55*mm, 40*mm, 25*mm])
        scmds = [
            ("BACKGROUND", (0,0), (-1,0), C_PRIMARY), ("TEXTCOLOR", (0,0), (-1,0), white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE", (0,0), (-1,-1), 8),
            ("ALIGN", (3,0), (3,-1), "CENTER"), ("GRID", (0,0), (-1,-1), 0.4, C_NEUTRAL),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [white, C_BG]),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4), ("TOPPADDING", (0,0), (-1,-1), 4),
        ]
        for i, r in enumerate(cra_results, 1):
            cl = self._sc(r["status"])
            scmds.append(("TEXTCOLOR", (3,i), (3,i), cl))
            scmds.append(("FONTNAME", (3,i), (3,i), "Helvetica-Bold"))
        et.setStyle(TableStyle(scmds))
        el.append(et)
        el.append(PageBreak())

        # Detailed Findings
        el.append(Paragraph(t("detailed_findings", lang), self.styles["QH1"]))
        for r in cra_results:
            cl = self._sc(r["status"])
            bl = []
            bl.append(Paragraph(
                f'<font color="{cl.hexval()}">[{r.get("status_display", r["status"])}]</font> '
                f'{r["article"]} — {r["title"]}',
                ParagraphStyle("FT", parent=self.styles["Normal"],
                    fontSize=10, fontName="Helvetica-Bold", textColor=C_PRIMARY, spaceAfter=1*mm)))
            bl.append(Paragraph(f'<b>{t("check", lang)}:</b> {r["check"]}', self.styles["QBody"]))
            if r.get("detail"):
                bl.append(Paragraph(f'<i>{r["detail"]}</i>', self.styles["QBody"]))
            if r.get("remediation") and r["remediation"] != t("no_action", lang):
                bl.append(Paragraph(f'<b>{t("remediation", lang)}:</b> {r["remediation"]}', self.styles["QBody"]))
            bl.append(Paragraph(f'<b>CRA:</b> {r["article"]} | <b>NIS2:</b> {r.get("nis2", "N/A")}', self.styles["QBody"]))
            bl.append(Spacer(1, 4*mm))
            el.append(KeepTogether(bl))

        # Recommendations
        el.append(PageBreak())
        el.append(Paragraph(t("recommendations", lang), self.styles["QH1"]))
        fails_list = [r for r in cra_results if r["status"] == "FAIL"]
        warns_list = [r for r in cra_results if r["status"] == "WARNING"]
        if fails_list:
            el.append(Paragraph(t("priority1", lang), self.styles["QH2"]))
            for r in fails_list:
                el.append(Paragraph(f'<b>{r["article"]}</b> — {r["title"]}: {r.get("remediation", "")}', self.styles["QBody"]))
        if warns_list:
            el.append(Paragraph(t("priority2", lang), self.styles["QH2"]))
            for r in warns_list:
                el.append(Paragraph(f'<b>{r["article"]}</b> — {r["title"]}: {r.get("remediation", "")}', self.styles["QBody"]))
        if not pqc:
            el.append(Paragraph(t("pqc_migration", lang), self.styles["QH2"]))
            el.append(Paragraph(t("pqc_migration_text", lang), self.styles["QBody"]))

        el.append(Spacer(1, 15*mm))
        el.append(Paragraph(f"{t('report_footer', lang)} v{VERSION} | {COMPANY} | {WEBSITE}", self.styles["QSmall"]))

        doc.build(el, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        return output_path
